### ISSUE TITLE
Strange answer of print

### ISSUE THREAD

**Issue by AlexisHuvier** [marcelogdeandrade/PythonCompiler#3]
Hey, i have the same code. I compile with clang but the executable say "-458475770" for this code :
`print(4 + 4 - 2);`

**Comment by aditya9126** [comment]
1>try using visual studio 
2> replace "utf-8" in codegen code to "latin1"

all the best!!!

**Comment by AlexisHuvier** [comment]
I remake the code but i have this error :
D:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `.\output.obj' is incompatible with i386:x86-64 output
.\output.obj:(.text+0x8): undefined reference to `_printf'
D:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o):crt0_c.c:(.text.startup+0x2e): undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status
